# -*- coding: utf-8 -*-
"""SPARK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XqD2AprVxzHgMDnIpSMlporWxCeO-4sj
"""

from pyspark import SparkContext

sc = SparkContext()

xyz= sc.parallelize([1,2,3,4,4,5,5,6])

#TO MANUALLY CHANGE THE NUMBER OF PARTITIONS WITHIN THE DEFINING PROCESS
# xyz= sc.parallelize([1,2,3,3,4,5,5,6],8) - THE RESULT WILL BE 8 PARTITIONS

type(xyz)

#TO SHOW ALL CONTENTS
xyz.collect()

xyz.take(2)

xyz.first()

#TO VERIFY NUMBER OF PARTITIONS OF RDD
xyz.getNumPartitions()

# TO CONVERT THE PARTITIONS - Purpose: Reduce number of partitions
abc = xyz.coalesce(1)
abc.getNumPartitions()

# TO INCREASE THE PARTITIONS - Purpose: Increase or decrease partitions with fll reshuffle
ram = abc.repartition(4)
ram.getNumPartitions()

#FILTER - conditions
words=sc.parallelize(["spark","Hadoopd","Hive","java","Python"])
words.getNumPartitions()
words_filter=words.filter(lambda x: "java" in x)
words_filter.collect()

#MAP - using to form data as a key,value pairs or split data with delimiter
#flatmap - using to split content of file with specific delimiter
myrdd=words.map(lambda x:(x,1))
myrdd.collect()

#REDUCEBYKEY - using to aggregate values by keywise ( no need to apply groupby)
# or AGGREGATEBYKEY - same purpose
myresults=myrdd.reduceByKey(lambda x,y:x+y)
myresults.collect()

"""myrdd = [
 ('A', 10),
 ('B', 20),
 ('A', 5),
 ('B', 30),
 ('A', 15)
]
myresults = myrdd.reduceByKey(lambda x, y: x + y)
myresults.collect()

[('A', 30), ('B', 50)]"""

myresults.getNumPartitions()

myresults.coalesce(1).saveAsTextFile("/content/sample_data/results.txt")

#flatmap - using to split content of file with specific delimiter

xyz=["rama laxman","iam in hyd","where r you","going to office for work"]
myrdd=sc.parallelize(xyz)
myrdd.collect()

myxyz=myrdd.flatMap(lambda x:x.split(" "))
myxyz.collect()

myxxyz=myrdd.map(lambda x:x.split(" "))
myxxyz.collect()

#TO CREATE THE RDD FOR THE FILES  OF HDFS
myabc=sc.textFile("/content/sample_data/war_and_peace.txt",4)

type(myabc)

myabc.take(5)

myabc.count()

myabc.cache()

#FIND THE WORD COUNT ?
myxyz=myabc.flatMap(lambda s:s.split(" "))
myxyz.count()

z=myxyz.map(lambda c:(c,1))
z.take(5)

x=z.reduceByKey(lambda x,y:x+y)
x.take(5)

x.count()

x.saveAsTextFile("/content/sample_data/cache_ouyput.txt")

moviesrdd=sc.textFile("/content/sample_data/movies.csv")
moviesrdd.count()
moviesrdd.first()

ratingsrdd=sc.textFile("/content/sample_data/ratings.csv")
ratingsrdd.count()

ratingsrdd.first()

moviesrdd.cache()

moviesrdd.count()

moviesrdd.take(10)

# To delete the first row
moviesdata=moviesrdd.filter(lambda line: not line.startswith("movieId"))
moviesdata.take(5)

header=ratingsrdd.first()
header

ratingsdata=ratingsrdd.filter(lambda line: line != header)
ratingsdata.take(5)

movies_by_movieid=moviesdata\
.map(lambda line : line.split(","))\
.map(lambda tokens : (tokens[0],tokens[1]))
movies_by_movieid.take(5)

ratings_by_movieid=ratingsdata\
.map(lambda line : line.split(","))\
.map(lambda tokens : (tokens[0],float(tokens[2])))
ratings_by_movieid.take(5)

movies_by_movieid.join(ratings_by_movieid).take(5)

from pyspark.sql import SparkSession
spark=SparkSession.builder.appName("Mydfanalysis").getOrCreate()

data=[("Alice",34),("Bob",40),("Cathy",29)]
columns=["Name","Age"]
df=spark.createDataFrame(data,columns)
df.show()
type(df)

df.select("Name").show()

df.filter(df.Age>30).show()

#to save ouput dataframe to hdfs

df.write.csv("/content/sample_data/emp.csv")
df.rdd.getNumPartitions()

#ADD NEW COLUMN : USING WITHCOLUMN : ADD THE NEW COLUMN TO THE DF

df=df.withColumn("Age_in_5_years",df.Age+5)
df.show()

df.printSchema()

mydf=spark.read.json("/content/sample_data/sales.json")
mydf.show()

mydf.printSchema()

titanic=sc.textFile("/content/sample_data/titanic_data.csv")
titanic.take(5)

mydf1=spark.read.csv("/content/sample_data/titanic_data.csv",header=True,inferSchema=True)

mydf1.show()

mydf1.write.orc("/content/sample_data/xyz.orc")

mydf2=spark.read.orc("/content/sample_data/xyz.orc")

mydf2.show()

mydf2.createOrReplaceTempView("titanic_tv")
spark.sql("select * from titanic_tv").show()

mydf3=spark.sql("select Sex from titanic_tv where Survived=1")
mydf3.show()

mydf2.createOrReplaceGlobalTempView("titanic_tv")
spark.sql("select * from titanic_tv").show()

mydf3=spark.sql("select Sex from titanic_tv where Survived=1")
mydf3.show()

from pyspark import StorageLevel
mydf3.persist(StorageLevel.MEMORY_AND_DISK)

mydf3.count()

#LARGE DATAFRAMES
employees = [(1,"ALice",5000),(2,"Bob",6000),(3,"Charlie",4000)]
df_large=spark.createDataFrame(employees,["id","name","salary"])
df_large.show()

#SMALL DATAFRAME
departments=[(1,"HR"),(2,"Sales"),(3,"IT")]
df_small=spark.createDataFrame(departments,["id","dept"])
df_small.show()

#REGULAR JOIN MORE TIME TAKEN - shuffle
joined=df_large.join(df_small,"id")
joined.show()

#Broadcast join - no shuffle fast
from pyspark.sql import functions as F

joined_broadcast=df_large.join(F.broadcast(df_small),"id")
joined_broadcast.show()

# TO REDUCE SHUFFLE PARTITIONS FOR SMALL DATASETS

spark.conf.set("spark.sql.shuffle.partitions","5")

#WINDOWS FUNCTION
from pyspark.sql import functions as F
from pyspark.sql import Window

data=[("Alice","Sales",5000),("Bob","Sales",6000),("Charlie","HR",4000),("David","HR",4500)]
df=spark.createDataFrame(data,["name","dept","salary"])
df.show()

windowSpec=Window.partitionBy("dept").orderBy(F.desc("Salary"))

df.withColumn("rank",F.rank().over(windowSpec)).show()

df.groupBy("dept").agg(F.avg("salary").alias("avg_salary")).show()

from pyspark.sql.functions import udf
from pyspark.sql.types import StringType

def categorize_salary(salary):
  return "High" if salary > 5000 else "Low"

salary_udf=udf(categorize_salary,StringType())

df.withColumn("salary_category",salary_udf(df["salary"])).show(  )

